### ISSUE TITLE
Can you provide your trained model

### ISSUE THREAD

**Issue by zhanglijia** [tynguyen/unsupervisedDeepHomographyRAL2018#1]
Hi, I don't have enough time to train this model, can you provide your trained model?

**Comment by zhanglijia** [comment]
Hi, excuse, I don't have enough time to train this model, can you provide your trained model?

**Comment by tynguyen** [comment]
Hi Zhanglijia, 
I have uploaded the trained models. Please go to README.md for more information.
You may also want to update the code since there is a slight change in the code.
