### ISSUE TITLE
finetune on fingerprint dataset

### ISSUE THREAD

**Issue by whqwill** [tynguyen/unsupervisedDeepHomographyRAL2018#14]
Hi,

I try to use the framework to finetune on fingerprint dataset, but the loss is very high and after several hours it is still very high, the loss dose not change. But I tried some other datasets, it works week. I want to know if this model is not suitable for the fingerprint.

**Comment by tynguyen** [comment]
Hi there,
There are a couple of possible reasons:
1. The displacement of a pixel between the two images is too big? Make sure
that it should not > 30%
2. The transformation is not homography?
3. There are distortions in parts of the images?

It's hard to tell correctly what is the reason without seeing the actual
images though.

**Comment by whqwill** [comment]
I made the pictures by gen_synthetic_data.py, the pictures are like this:

![121](https://user-images.githubusercontent.com/7381876/68288723-eb05c980-00bf-11ea-8913-e3e40e49a85c.jpg)
![120](https://user-images.githubusercontent.com/7381876/68288725-eb9e6000-00bf-11ea-90fb-8ef130fc1a50.jpg)
![119](https://user-images.githubusercontent.com/7381876/68288730-eccf8d00-00bf-11ea-94d3-6cba52ffa986.jpg)
![118](https://user-images.githubusercontent.com/7381876/68288732-ed682380-00bf-11ea-93cb-5bf4e2367502.jpg)
![117](https://user-images.githubusercontent.com/7381876/68288735-ee00ba00-00bf-11ea-820d-6d226ebc70f8.jpg)
![116](https://user-images.githubusercontent.com/7381876/68288736-ee00ba00-00bf-11ea-8c6d-15534fad241a.jpg)

but I tried other pictures like this, it works very well:
![121](https://user-images.githubusercontent.com/7381876/68288956-4a63d980-00c0-11ea-9619-e1c5033e40b3.jpg)
![120](https://user-images.githubusercontent.com/7381876/68288958-4a63d980-00c0-11ea-8917-a42562d62336.jpg)
![119](https://user-images.githubusercontent.com/7381876/68288960-4afc7000-00c0-11ea-8415-6fc1eefb7fb7.jpg)
![118](https://user-images.githubusercontent.com/7381876/68288961-4afc7000-00c0-11ea-8e76-59c968f3f21c.jpg)
![117](https://user-images.githubusercontent.com/7381876/68288963-4b950680-00c0-11ea-98ef-c7c94684b561.jpg)
![116](https://user-images.githubusercontent.com/7381876/68288965-4c2d9d00-00c0-11ea-9803-69434931a700.jpg)
![115](https://user-images.githubusercontent.com/7381876/68288966-4c2d9d00-00c0-11ea-8617-bbf4d23cfe63.jpg)
![114](https://user-images.githubusercontent.com/7381876/68288969-4cc63380-00c0-11ea-9abc-ae1215605d78.jpg)
