### ISSUE TITLE
how to get Homography matrix?

### ISSUE THREAD

**Issue by steve13durant** [tynguyen/unsupervisedDeepHomographyRAL2018#23]
I found the test result is pts2_pred value, how can I predict Homography matrix with two frames?

**Comment by tynguyen** [comment]
You can refer to this function: 
pred_h4p, _, not_found  = ransac_h.find_homography(I_sample, I_prime_sample, pts_1, pts_2, visual=args.visual, method=args.method, min_match_count=args.num_features)
Where pts_2 = pts_1 + pts2_pred 
More details can be found in: 
**code/homography_conventional_synthetic.py**
