### ISSUE TITLE
Sports and Soccer video

### ISSUE THREAD

**Issue by AhmedKhaled945** [tynguyen/unsupervisedDeepHomographyRAL2018#24]
Hello, Thanks for this contribution, i'm really interested in trying to run this module on Soccer broadcast registration problem,

What do you think? should i create my own dataset, or can the trained weights you provided work on this kind of problem?
Any recommendation would be appreciated,
Thanks.

**Comment by tynguyen** [comment]
Sorry if my email has not sent to you.  Yes, I think this homography can be a good solution. You might want to finetune using your own dataset.
