### ISSUE TITLE
Final aggregated MACE

### ISSUE THREAD

**Issue by dkoguciuk** [tynguyen/unsupervisedDeepHomographyRAL2018#25]
Hi @tynguyen ,

what is the final MACE of your model? You've broken down the metric into overlap and percentile, but I can't find the final MACE just like in DeTone paper.

Best,
Daniel

**Comment by tynguyen** [comment]
We used RMSE instead of MACE. You can refer to Fig.4 for the comparison between approaches w.r.t RMSE.
