### ISSUE TITLE
RMSE/MACE of supervised and unsupervised methods

### ISSUE THREAD

**Issue by dkoguciuk** [tynguyen/unsupervisedDeepHomographyRAL2018#26]
Hi @tynguyen ,

thank you for your reply [HERE](https://github.com/tynguyen/unsupervisedDeepHomographyRAL2018/issues/25). Since you've closed my issue I had to start a new one. I've downloaded your pretrained models and modified the code to output aggregated MACE and RMSE and got as follows:

SUPERVISED:
```
|Steps  |   h_loss   |    l1_loss   |  Fail percent    |
119 12.241411097844441 0.6906676491101583 6.328125
>> Top 0 -  30 %
>> Top 30 -  60 %
>> Top 60 -  100 %
===> Percentile Values: (20, 50, 80, 100):
[[11.565539    0.36131516]
 [12.173439    0.16126795]
 [12.799296    0.27282068]]
======> End! ====================================
MACE 10.368597
RMSE 14.589684
```

UNSUPERVISED:
```
|Steps  |   h_loss   |    l1_loss   |  Fail percent    |
119 14.196217513084411 0.6258547094961008 19.4140625
>> Top 0 -  30 %
>> Top 30 -  60 %
>> Top 60 -  100 %
===> Percentile Values: (20, 50, 80, 100):
[[13.357981    0.33709136]
 [14.083497    0.1984129 ]
 [14.909436    0.37759867]]
======> End! ====================================
MACE 12.908667
RMSE 19.376993
```

Here's the MACE/RMSE calculation snippet:
```

daniel_gt_4p = []
daniel_pred_4p = []

for step in range(self.num_total_steps):
    num_fail_value, h_loss_value,  rec_loss_value, ssim_loss_value, l1_loss_value, l1_smooth_loss_value,  pred_I2_value, I1_aug_value, I2_aug_value, I_value, I_prime_value, pts1_value, gt_value, pred_h4p_value  = sess.run([self.total_num_fail, self.total_h_loss, self.total_rec_loss, self.total_ssim_loss, self.total_l1_loss, self.total_l1_smooth_loss, self.pred_I2, self.I1_aug, self.I2_aug, self.I, self.I_prime, self.pts1, self.gt, self.pred_h4p])

    daniel_gt_4p.append(gt_value)
    daniel_pred_4p.append(pred_h4p_value)

(...)

print('MACE', np.mean(np.abs(np.array(daniel_gt_4p) - np.array(daniel_pred_4p))))
print('RMSE', np.sqrt(np.mean((np.array(daniel_gt_4p)- np.array(daniel_pred_4p))**2)))
```

Now I am a bit confused. In your paper, in figure 4 you've reported RMSE of supervised method about 35 and RMSE of unsupervised about 13. So, according to your paper unsupervised method should be MUCH better than the supervised, but it's not the case with your provided models. I've seen others got similar results [HERE](https://github.com/tynguyen/unsupervisedDeepHomographyRAL2018/issues/7), but instead of commenting on that, you've closed the issue.

Is my understanding of figure 4 wrong? 

Best,
Daniel

**Comment by tynguyen** [comment]
Thanks for your efforts. I think your computation is correct and it does not contradict what shown in Fig.4. 
Indeed, Fig. 4 shows results on the "real" Aerial Images, not "synthetic" test set.

**Comment by dkoguciuk** [comment]
Oh, right. My bad. Thanks, @tynguyen for clarifying this :)
