### ISSUE TITLE
Relationship between total number of steps and epochs

### ISSUE THREAD

**Issue by NagarajDesai1** [tynguyen/unsupervisedDeepHomographyRAL2018#27]
Hi @tyunist ,

Thanks for your code. 

I have a question regarding the synthetic training script. 

you have set `num_total_steps = 150000 ` [here](https://github.com/tynguyen/unsupervisedDeepHomographyRAL2018/blob/master/code/homography_CNN_synthetic.py#L161)

And I see that batch size is 128

Could you please explain why did you select these values and how can i determine the total number of epochs using `num_total_steps`?

Best regards,
Nagaraj

**Comment by tynguyen** [comment]
Sorry for this late rep. These numbers are mainly found empirically.
