### ISSUE TITLE
Using the model on own real homography dataset

### ISSUE THREAD

**Issue by yuvalH9** [tynguyen/unsupervisedDeepHomographyRAL2018#28]
Hi there,

I'm trying to run your model on real homograpy dataset (like the one provided [here](http://kahlan.eps.surrey.ac.uk/featurespace/web/data.htm) which includes the real GT homography matrix) in order to estimate the homography between two images of the same scene taken from different angles.

I assume that I will need to run `homography_CNN_real.py`, but when I'm generating the test dataset using `gen_real_data.py` your code goes to `query_gt_test_set()` with some hardcoded params refer to the aerial dataset which is not supplied.

Can you please explain what exact inputs are needed for `homography_CNN_real.py` when I'm using my own data,
especially what should be in `--test_gt_file` and what exact preprocessing steps needed to fit my own data to the NN.

I see that the repository is kind of inactive for a while, hope the author (or anyone else who encountered same issue)  will help.

Regards,
Yuval

**Comment by tynguyen** [comment]
They are basically 4-point correspondences between every pair of images.
