### ISSUE TITLE
Error in FineTuning the Model

### ISSUE THREAD

**Issue by nayeemiiitd** [tynguyen/unsupervisedDeepHomographyRAL2018#4]
After downloading the Pretrained model on synthetic dataset and storing it in models directory. I ran the homography_CNN_real.py script, but it gave the error as: 

![e1](https://user-images.githubusercontent.com/15953413/38831897-73499986-41de-11e8-8eeb-8267c0af1f3e.png)

I have done the preprocessing of my dataset using gen_real_data.py script. I was using l1_loss for finetuning the network.

**Comment by tynguyen** [comment]
I guess the issue come when you set  --batch_norm to be True. 

Can you try not using batchnorm? When I trained the network, using batchnorm is inferior I set it off.

**Comment by nayeemiiitd** [comment]
I tried setting --use_batch_norm as False, but still the same error.

**Comment by NBUWang** [comment]
I have the same issue with nayeemiiitd.@nayeemiiitd

**Comment by tyunist** [comment]
Hi there, this bug has been fixed! 

Thanks

**Comment by shangrongyang** [comment]
Excuse me, when i run the homography_CNN_synthetic.py
I had meet the error : TypeError: cannot create weak reference to 'builtin_function_or_method' object
Do you know how to solve this problem?
