### ISSUE TITLE
A small bug 

### ISSUE THREAD

**Issue by ruiwen0615** [tynguyen/unsupervisedDeepHomographyRAL2018#5]
In gen_synthetic_data.py, line 63 should be inv instead of iinv

**Comment by tyunist** [comment]
fixed it, thanks!

**Comment by shangrongyang** [comment]
Excuse me, when i run the homography_CNN_synthetic.py
I had meet the error :   TypeError: cannot create weak reference to 'builtin_function_or_method' object
Do you know how to solve this problem?
