### ISSUE TITLE
Test with own images

### ISSUE THREAD

**Issue by guist** [tynguyen/unsupervisedDeepHomographyRAL2018#6]
Hello,

I want to find the homography between two images of the same scene captured by two cameras with different orientations, based on 4 co-planar points visible in both images. I would like to test your framework but I am not sure which piece of code I should use and which extra information I should provide:
-> to use: homogaphy_CNN_real.py or homography_CNN_synthetic.py?
-> to provide: at least folder with the two images (DATA_PATH), text file with the image names (FILENAMES_FILE), text file with the coordinates of the 4 co-planar points in one image (PTS1_FILE), anything else?

I guess I do not have to modify any parameters related to the training, the ground truth, etc?

Thank you for your answer!

Best regards,
Guillaume

**Comment by tyunist** [comment]
Hi, 

Please be advised to use utils/gen_real_data.py with proper parameters to generate your data samples (a pair of image patches, first four points...). The most important thing is to crop your two images so as to feed the network. Depend on how large of the displacement between the two cameras, you may choose a proper-crop size;  If you have some prior about where the two images overlap, you can change the position of the crop. If not, just do center-crop as it does now. 

After that, homogaphy_CNN_real.py is used to train and test the network.
